CXX		= g++
SOURCE	= $(wildcard *.cpp)
OBJECT	= $(SOURCE:.cpp=.o)
CFLAGS = -std=c++17 -Wall -O2 -fPIC -Wall -g -c -D__cplusplus=201703L
INCLUDE = -I/usr/include/opencv4/ -I/usr/include
INCLUDE += -I../../Include
LIB = -L/opt/sdsol/lib -L/usr/local/lib -L./lib/armhf  -lppe -lpthread -lrt -ljsoncpp 
LIB += $(shell pkg-config --cflags --libs opencv4)

#LIB += -lopencv_alphamat -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_highgui -lopencv_datasets -lopencv_text -lopencv_plot -lopencv_ml -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_ximgproc -lopencv_video -lopencv_dnn -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core

TARGET  = test_estimate

.SUFFIXES : .o .cpp
%.o:%.cpp
	$(CXX) $(INCLUDE) $(CFLAGS) $< -o $(basename $@).o 

all : $(TARGET)

$(TARGET) : $(OBJECT)
	$(CXX) -o $@ $(OBJECT) $(LIB)
#	cp $(TARGET) /opt/sdsol/bin
	
clean :
	rm -rf *.o $(TARGET)
